export type Testament = "OT" | "NT";

export interface BibleBook {
  engName: string;
  chiName: string;
  abbr: string;
  testament: Testament;
  totalChapters: number;
}

export const BIBLE_BOOKS: BibleBook[] = [
  // ─── OLD TESTAMENT ────────────────────────────────
  {
    engName: "Genesis",
    chiName: "创世记",
    abbr: "GEN",
    testament: "OT",
    totalChapters: 50,
  },
  {
    engName: "Exodus",
    chiName: "出埃及记",
    abbr: "EXO",
    testament: "OT",
    totalChapters: 40,
  },
  {
    engName: "Leviticus",
    chiName: "利未记",
    abbr: "LEV",
    testament: "OT",
    totalChapters: 27,
  },
  {
    engName: "Numbers",
    chiName: "民数记",
    abbr: "NUM",
    testament: "OT",
    totalChapters: 36,
  },
  {
    engName: "Deuteronomy",
    chiName: "申命记",
    abbr: "DEU",
    testament: "OT",
    totalChapters: 34,
  },
  {
    engName: "Joshua",
    chiName: "约书亚记",
    abbr: "JOS",
    testament: "OT",
    totalChapters: 24,
  },
  {
    engName: "Judges",
    chiName: "士师记",
    abbr: "JDG",
    testament: "OT",
    totalChapters: 21,
  },
  {
    engName: "Ruth",
    chiName: "路得记",
    abbr: "RUT",
    testament: "OT",
    totalChapters: 4,
  },
  {
    engName: "1 Samuel",
    chiName: "撒母耳记上",
    abbr: "1SA",
    testament: "OT",
    totalChapters: 31,
  },
  {
    engName: "2 Samuel",
    chiName: "撒母耳记下",
    abbr: "2SA",
    testament: "OT",
    totalChapters: 24,
  },
  {
    engName: "1 Kings",
    chiName: "列王纪上",
    abbr: "1KI",
    testament: "OT",
    totalChapters: 22,
  },
  {
    engName: "2 Kings",
    chiName: "列王纪下",
    abbr: "2KI",
    testament: "OT",
    totalChapters: 25,
  },
  {
    engName: "1 Chronicles",
    chiName: "历代志上",
    abbr: "1CH",
    testament: "OT",
    totalChapters: 29,
  },
  {
    engName: "2 Chronicles",
    chiName: "历代志下",
    abbr: "2CH",
    testament: "OT",
    totalChapters: 36,
  },
  {
    engName: "Ezra",
    chiName: "以斯拉记",
    abbr: "EZR",
    testament: "OT",
    totalChapters: 10,
  },
  {
    engName: "Nehemiah",
    chiName: "尼希米记",
    abbr: "NEH",
    testament: "OT",
    totalChapters: 13,
  },
  {
    engName: "Esther",
    chiName: "以斯帖记",
    abbr: "EST",
    testament: "OT",
    totalChapters: 10,
  },
  {
    engName: "Job",
    chiName: "约伯记",
    abbr: "JOB",
    testament: "OT",
    totalChapters: 42,
  },
  {
    engName: "Psalm",
    chiName: "诗篇",
    abbr: "PSA",
    testament: "OT",
    totalChapters: 150,
  },
  {
    engName: "Proverbs",
    chiName: "箴言",
    abbr: "PRO",
    testament: "OT",
    totalChapters: 31,
  },
  {
    engName: "Ecclesiastes",
    chiName: "传道书",
    abbr: "ECC",
    testament: "OT",
    totalChapters: 12,
  },
  {
    engName: "Song of Solomon",
    chiName: "雅歌",
    abbr: "SNG",
    testament: "OT",
    totalChapters: 8,
  },
  {
    engName: "Isaiah",
    chiName: "以赛亚书",
    abbr: "ISA",
    testament: "OT",
    totalChapters: 66,
  },
  {
    engName: "Jeremiah",
    chiName: "耶利米书",
    abbr: "JER",
    testament: "OT",
    totalChapters: 52,
  },
  {
    engName: "Lamentations",
    chiName: "耶利米哀歌",
    abbr: "LAM",
    testament: "OT",
    totalChapters: 5,
  },
  {
    engName: "Ezekiel",
    chiName: "以西结书",
    abbr: "EZK",
    testament: "OT",
    totalChapters: 48,
  },
  {
    engName: "Daniel",
    chiName: "但以理书",
    abbr: "DAN",
    testament: "OT",
    totalChapters: 12,
  },
  {
    engName: "Hosea",
    chiName: "何西阿书",
    abbr: "HOS",
    testament: "OT",
    totalChapters: 14,
  },
  {
    engName: "Joel",
    chiName: "约珥书",
    abbr: "JOE",
    testament: "OT",
    totalChapters: 3,
  },
  {
    engName: "Amos",
    chiName: "阿摩司书",
    abbr: "AMO",
    testament: "OT",
    totalChapters: 9,
  },
  {
    engName: "Obadiah",
    chiName: "俄巴底亚书",
    abbr: "OBA",
    testament: "OT",
    totalChapters: 1,
  },
  {
    engName: "Jonah",
    chiName: "约拿书",
    abbr: "JON",
    testament: "OT",
    totalChapters: 4,
  },
  {
    engName: "Micah",
    chiName: "弥迦书",
    abbr: "MIC",
    testament: "OT",
    totalChapters: 7,
  },
  {
    engName: "Nahum",
    chiName: "那鸿书",
    abbr: "NAH",
    testament: "OT",
    totalChapters: 3,
  },
  {
    engName: "Habakkuk",
    chiName: "哈巴谷书",
    abbr: "HAB",
    testament: "OT",
    totalChapters: 3,
  },
  {
    engName: "Zephaniah",
    chiName: "西番雅书",
    abbr: "ZEP",
    testament: "OT",
    totalChapters: 3,
  },
  {
    engName: "Haggai",
    chiName: "哈该书",
    abbr: "HAG",
    testament: "OT",
    totalChapters: 2,
  },
  {
    engName: "Zechariah",
    chiName: "撒迦利亚书",
    abbr: "ZEC",
    testament: "OT",
    totalChapters: 14,
  },
  {
    engName: "Malachi",
    chiName: "玛拉基书",
    abbr: "MAL",
    testament: "OT",
    totalChapters: 4,
  },

  // ─── NEW TESTAMENT ────────────────────────────────
  {
    engName: "Matthew",
    chiName: "马太福音",
    abbr: "MAT",
    testament: "NT",
    totalChapters: 28,
  },
  {
    engName: "Mark",
    chiName: "马可福音",
    abbr: "MRK",
    testament: "NT",
    totalChapters: 16,
  },
  {
    engName: "Luke",
    chiName: "路加福音",
    abbr: "LUK",
    testament: "NT",
    totalChapters: 24,
  },
  {
    engName: "John",
    chiName: "约翰福音",
    abbr: "JHN",
    testament: "NT",
    totalChapters: 21,
  },
  {
    engName: "Acts",
    chiName: "使徒行传",
    abbr: "ACT",
    testament: "NT",
    totalChapters: 28,
  },
  {
    engName: "Romans",
    chiName: "罗马书",
    abbr: "ROM",
    testament: "NT",
    totalChapters: 16,
  },
  {
    engName: "1 Corinthians",
    chiName: "哥林多前书",
    abbr: "1CO",
    testament: "NT",
    totalChapters: 16,
  },
  {
    engName: "2 Corinthians",
    chiName: "哥林多后书",
    abbr: "2CO",
    testament: "NT",
    totalChapters: 13,
  },
  {
    engName: "Galatians",
    chiName: "加拉太书",
    abbr: "GAL",
    testament: "NT",
    totalChapters: 6,
  },
  {
    engName: "Ephesians",
    chiName: "以弗所书",
    abbr: "EPH",
    testament: "NT",
    totalChapters: 6,
  },
  {
    engName: "Philippians",
    chiName: "腓立比书",
    abbr: "PHP",
    testament: "NT",
    totalChapters: 4,
  },
  {
    engName: "Colossians",
    chiName: "歌罗西书",
    abbr: "COL",
    testament: "NT",
    totalChapters: 4,
  },
  {
    engName: "1 Thessalonians",
    chiName: "帖撒罗尼迦前书",
    abbr: "1TH",
    testament: "NT",
    totalChapters: 5,
  },
  {
    engName: "2 Thessalonians",
    chiName: "帖撒罗尼迦后书",
    abbr: "2TH",
    testament: "NT",
    totalChapters: 3,
  },
  {
    engName: "1 Timothy",
    chiName: "提摩太前书",
    abbr: "1TI",
    testament: "NT",
    totalChapters: 6,
  },
  {
    engName: "2 Timothy",
    chiName: "提摩太后书",
    abbr: "2TI",
    testament: "NT",
    totalChapters: 4,
  },
  {
    engName: "Titus",
    chiName: "提多书",
    abbr: "TIT",
    testament: "NT",
    totalChapters: 3,
  },
  {
    engName: "Philemon",
    chiName: "腓利门书",
    abbr: "PHM",
    testament: "NT",
    totalChapters: 1,
  },
  {
    engName: "Hebrews",
    chiName: "希伯来书",
    abbr: "HEB",
    testament: "NT",
    totalChapters: 13,
  },
  {
    engName: "James",
    chiName: "雅各书",
    abbr: "JAS",
    testament: "NT",
    totalChapters: 5,
  },
  {
    engName: "1 Peter",
    chiName: "彼得前书",
    abbr: "1PE",
    testament: "NT",
    totalChapters: 5,
  },
  {
    engName: "2 Peter",
    chiName: "彼得后书",
    abbr: "2PE",
    testament: "NT",
    totalChapters: 3,
  },
  {
    engName: "1 John",
    chiName: "约翰一书",
    abbr: "1JN",
    testament: "NT",
    totalChapters: 5,
  },
  {
    engName: "2 John",
    chiName: "约翰二书",
    abbr: "2JN",
    testament: "NT",
    totalChapters: 1,
  },
  {
    engName: "3 John",
    chiName: "约翰三书",
    abbr: "3JN",
    testament: "NT",
    totalChapters: 1,
  },
  {
    engName: "Jude",
    chiName: "犹大书",
    abbr: "JUD",
    testament: "NT",
    totalChapters: 1,
  },
  {
    engName: "Revelation",
    chiName: "启示录",
    abbr: "REV",
    testament: "NT",
    totalChapters: 22,
  },
];

export interface BibleVerseSelection {
  book: string;
  chapter: number;
  verseStart: number;
  verseEnd: number;
}

export function formatSelection(selection: BibleVerseSelection): string {
  const { book, chapter, verseStart, verseEnd } = selection;
  if (verseStart === verseEnd) {
    return `${book} ${chapter}:${verseStart}`;
  }
  return `${book} ${chapter}:${verseStart}-${verseEnd}`;
}
